#!/bin/bash
# ffmpeg -f v4l2 -pix_fmt mjpeg -i /dev/video-webcam0 -f alsa -i hw:2 -c:v libx264 -g 50 -level:v 4.1 -preset:v superfast -tune:v zerolatency -b:v 4M -b:a 256k -c:a libopus -f rtsp rtsp://192.168.40.113:8554/Laboratory

ffmpeg -f v4l2 -pix_fmt mjpeg -i /dev/video-webcam0 -c:v libx264 -g 50 -level:v 4.1 -preset:v superfast -tune:v zerolatency -bf 0 -b:v 3M -f rtsp rtsp://192.168.40.113:8554/Laboratory
